### ISSUE TITLE
Feature request: using bolero in other languages

### ISSUE THREAD

**Issue by ckaran** [camshaft/bolero#48]
This is a *very* long-term feature request, please put it down as a low priority.

Bolero is my go-to tool for testing all of my code in rust.  Unfortunately, I can't use rust everywhere; in particular, I have to use C++ at my day job.  Is there any way to make bolero work with C/C++ with a minimum of effort?  If not, I'll spend the time figuring out FFI bindings (if you think that will work).

**Comment by Ekleog** [comment]
Do you have an example of what "make bolero work with C/C++ with a minimum of effort" would look like to you? I can't think of what exactly that would encompass.

If you mean "does not go through cargo" and/or "automatically generates c++ types", my guess would be it's impossible (the second one would be best accomplished through the `cxx` crate but it's quite rust-heavy). And without it, I'm not sure whether it'd make sense to say "bolero works with c++"

**Comment by ckaran** [comment]
Unfortunately, I don't have a precise definition I can give you.  Either of the suggestions you made would be fine by me.

The other **MUCH** more heavy-handed approach would be to use some kind of IPC mechanism, but I suspect that would open its own can of worms.

**Comment by Ekleog** [comment]
Hmm so IPC would break libfuzzer instrumentation: the code on the other side of the IPC would need a way to report which branches were taken to the fuzzer, and that'd be very hard indeed.

I don't think bolero without cargo would make sense: the whole reason of bolero's existence is that it integrates well with cargo; without that cargo-fuzz would be just as good.

Currently, my best idea of what the code could look like would be (pardon my rusty c++ -- pun not intended):
```cpp
struct Input {
    // ...
};
bool fuzz_with(input: Input) {
    // ... return true if it worked, false if not
}
```
```rust
#[cxx::bridge]
mod ffi {
    // define the Input struct and fuzz_with fn here
}
#[derive(TypeGenerator)]
struct Input {
    // ...
}
fn rs_to_cxx(i: Input) -> ffi::Input {
    // convert from Input to c++'s Input
}
#[test]
fn fuzz_it() {
    bolero::check!().with_type().for_each(|i| assert!(ffi::fuzz_with(rs_to_cxx(i)));
}
```

The thing is… I don't see what more bolero could do to support that use case than it already does :sweat_smile: 

The biggest idea I could think of to improve upon this code would be automatically deriving the c++ type rather than manually having to write it again in Input and the rs_to_cxx function… but that's actually something that could (and probably should) happen outside of bolero, as it'd also be useful for other projects. (eg. having `Debug` on cxx types)

For instance, this feels like it could maybe make its way into `autocxx`, though I only heard of it quite recently and don't know how production-ready it is.

Does what I'm saying make sense?

**Comment by ckaran** [comment]
It does make sense, and if you don't think it's appropriate for Bolero, then that is that.  Like you, I've heard of `autocxx`, but I don't know anything about it, or how good it is.  So, I guess it's appropriate to close this at this point.

**Comment by Ekleog** [comment]
Just as a disclaimer, I'm not the maintainer of Bolero, @camshaft is; I'm just a contributor combing through the backlog because I really like it! That said I guess for this issue to be actionable it'd need some more context on what exactly you'd want bolero to do more, and I personally can't think of anything that would be in-scope for bolero and would not better be done as external crates that could then be reused in non-fuzzing contexts, so I'm personally in favor of closing too :)

**Comment by ckaran** [comment]
> so I'm personally in favor of closing too and maybe starting a discussion with autocxx on how to auto-derive traits from rust on c++ structs :)

That's a really good idea!  Do you know the maintainers of autocxx?  If not, I'll try to put together a feature request for this to them.

**Comment by Ekleog** [comment]
I don't know anything more than the fact it lies at https://github.com/google/autocxx ; sorry :sweat_smile:

**Comment by ckaran** [comment]
Ah well.  I'll have to spend some time to think about how to write up this feature request for them.
